### ISSUE TITLE
Resource: Other similar project/s

### ISSUE THREAD

**Issue by mubashir-rehman** [mars885/doc-skanner#2]
I found this project recently when a person i follow starred it. I hope it does a great job. I am linking a similar project here in case it might help someone. https://github.com/Ethereal-Developers-Inc/OpenScan

**Comment by mars885** [comment]
That's great. I probably won't put it in the resources section, since I personally have not used/seen the repo you mentioned. I'm sure a simple Google search will be enough to find it. Closing it for now, since it is not an issue per se.
